<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250202201124 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tracking_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type INT NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, session_id VARCHAR(255) NOT NULL, user_id INT DEFAULT NULL, details JSON NOT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE tracking_event');
    }
}
